<?php

$candidates_dbr_2019 = array(
    array('id'=>1, 'name'=>"Апасов Василь Олександрович",
          'org'=>"Міжнародна громадська організація «Українське козацтво»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Apasov.pdf"),
    array('id'=>2, 'name'=>"Безпалий Тарас Геннадійович",
          'org'=>"ВГО «Асоціація правників України»",
	  'link'=>"https://dbr.gov.ua/sites/default/files/Bezpaluy.pdf"),
    /*
    array('id'=>3, 'name'=>"Бойко Тарас Орестович",
          'org'=>"«Центр правових та політичних досліджень «СІМ»",
	  'link'=>"https://dbr.gov.ua/sites/default/files/Boyko.pdf"),
     */
    array('id'=>4, 'name'=>"Болдін Максим Якович",
          'org'=>"«Центр правового аналізу та дослідження політичних ризиків»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Boldin.pdf"),
    array('id'=>5, 'name'=>"Гілін Євген Олександрович",
          'org'=>"«Єдиний щит»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Gilin.pdf"),
    array('id'=>6, 'name'=>"Григоренко Юрій Сергійович",
          'org'=>"«Всеукраїнська незалежна науково-дослідна експертна спілка»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Grigorenko.pdf"),
    array('id'=>7, 'name'=>"Гриценко Олексій Анатолійович",
          'org'=>"«Всеукраїнське об'єднання «Автомайдан»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Gritsenko.pdf"),
    array('id'=>8, 'name'=>"Дарсанія Леван Валер'янович",
          'org'=>"ХОГПО «Опора «Слобожанщини»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Darsaniya.pdf"),
    array('id'=>9, 'name'=>"Детюк Андрій Миколайович",
          'org'=>"«Громадське об’єднання «Здорове суспільство»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Detyuk.pdf"),
    array('id'=>10, 'name'=>"Дяденко Михайло Васильович",
          'org'=>"«Центр правового аналізу та дослідження політичних ризиків»",
	  'link'=>"https://dbr.gov.ua/sites/default/files/Dyadenko.pdf"),
    /*
    array('id'=>11, 'name'=>"Заблоцький Мар’ян Богданович",
          'org'=>"«Українське товариство економічних свобод»",
	  'link'=>"https://dbr.gov.ua/sites/default/files/Zabolotskiy.pdf"),
     */
    array('id'=>12, 'name'=>"Золотар Степан Андрійович",
          'org'=>"«Асоціація українських моніторів дотримання прав людини в діяльності правоохоронних органів»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Zolotar.pdf"),
    array('id'=>13, 'name'=>"Іванов Сергій Володимирович",
          'org'=>"«Громадський люстраційний комітет»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Ivanov.pdf"),
    array('id'=>14, 'name'=>"Каменєв Михайло Володимирович",
          'org'=>"«Асоціація українських моніторів дотримання прав людини в діяльності правоохоронних органів»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Kamenev.pdf"),
    array('id'=>15, 'name'=>"Касьян Ольга Олександрівна",
          'org'=>"«Молодіжна організація «Заради майбутнього України»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Kasyan.pdf"),
    array('id'=>16, 'name'=>"Колесников Денис Вікторович",
          'org'=>"«Громадяни Дніпропетровщини»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Kolesnikov.pdf"),
    array('id'=>17, 'name'=>"Корінна Надія Миколаївна",
          'org'=>"«Центр правового аналізу та дослідження політичних ризиків»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Korinna.pdf"),
    array('id'=>18, 'name'=>"Коротюк Михайло Геннадійович",
          'org'=>"«Комітет з питань захисту прав потерпілих від злочинів»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Korotuk.pdf"),
    array('id'=>19, 'name'=>"Крапивін Євген Олексійович",
          'org'=>"«Асоціація українських моніторів дотримання прав людини в діяльності правоохоронних органів»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Krapuvin.pdf"),
    array('id'=>20, 'name'=>"Кувіта Катерина Юріївна",
          'org'=>"Міжнародна громадська організація «Українське козацтво»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Kuvita.pdf"),
    array('id'=>21, 'name'=>"Лємєнов Олександр Валерійович",
          'org'=>"«Стейтвотч»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Lemenov.pdf"),
    array('id'=>22, 'name'=>"Мамченко Наталя Сергіївна",
          'org'=>"«Центр протидії корупції в органах влади»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Mamchenko.pdf"),
    array('id'=>23, 'name'=>"Мартинюк Юрій Анатолійович",
          'org'=>"«Народна самооборона Львівщини»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Martunyk.pdf"),
    array('id'=>24, 'name'=>"Марчук Максим Едуардович",
          'org'=>"ВГО «СГОУ «Народна Рада»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Marchuk.pdf"),
    array('id'=>25, 'name'=>"Миланич Андрій Михайлович",
          'org'=>"ВГО «Асоціація правників України»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Melanych.pdf"),
    array('id'=>26, 'name'=>"Мізрах Ігор Аркадійович",
          'org'=>"ВГО «СГОУ «Народна Рада»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Mizpah.pdf"),
    array('id'=>27, 'name'=>"Новицький Данііл Євгенович",
          'org'=>"«Молодіжна організація «Заради майбутнього України»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Novitskiy.pdf"),
    array('id'=>28, 'name'=>"Носанов Данило Максимович",
          'org'=>"«Ерлайт»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Nosanov.pdf"),
    array('id'=>29, 'name'=>"Опанащук Віталій Степанович",
          'org'=>"Міжнародна громадська організація «Українське козацтво»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Opanashyk.pdf"),
    array('id'=>30, 'name'=>"Перова Ксенія Юріївна",
          'org'=>"ВГО «СГОУ «Народна Рада»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Perova.pdf"),
    array('id'=>31, 'name'=>"Петраковський Володимир Володимирович",
          'org'=>"Центр політико-правових реформ",
          'link'=>"https://dbr.gov.ua/sites/default/files/Petrakovskiy.pdf"),
    array('id'=>32, 'name'=>"Попович Ростислав Ігорович",
          'org'=>"«Український суспільно-правовий рух: демократія через право»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Popovich.pdf"),
    array('id'=>33, 'name'=>"Реплянчук Дмитро Олександрович",
          'org'=>"«Всеукраїнське об'єднання «Автомайдан»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Replyanchuk.pdf"),
    array('id'=>34, 'name'=>"Рябець Олександр Михайлович",
          'org'=>"«Спілка юристів Одеської області»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Ryabets.pdf"),
    array('id'=>35, 'name'=>"Савенко Євген Володимирович",
          'org'=>"«Всеукраїнська організація «Авто Евро Сила»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Savenko.pdf"),
    array('id'=>36, 'name'=>"Секела Руслан Михайлович",
          'org'=>"«Військово-патріотичне об’єднання «ВОЛЯ»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Sekela.pdf"),
    array('id'=>37, 'name'=>"Ставицька Ольга Олександрівна",
          'org'=>"«Громадяни Дніпропетровщини»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Stavitska.pdf"),
    array('id'=>38, 'name'=>"Удовіченко Костянтин Ігорович",
          'org'=>"«Молодіжна організація «Заради майбутнього України»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Udovichenko.pdf"),
    array('id'=>39, 'name'=>"Хавронюк Ярослав Миколайович",
          'org'=>"«Стейтвотч»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Khavrohyk.pdf"),
    array('id'=>40, 'name'=>"Хаджинов Сергій Володимирович",
          'org'=>"«Всеукраїнське об'єднання «Автомайдан»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Khadzhunov.pdf"),
    array('id'=>41, 'name'=>"Шевченко Павло Васильович",
          'org'=>"«Громадське об’єднання «Здорове суспільство»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Shevchenko.pdf"),
    array('id'=>42, 'name'=>"Шелестак Наталія Володимирівна",
          'org'=>"«Варта 700»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Shelestak.pdf"),
    array('id'=>43, 'name'=>"Шило Ганна Сергіївна",
          'org'=>"«Громадяни Дніпропетровщини»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Shylo.pdf")
);

$candidates_dbr_test = array(
    array('id'=>1, 'name'=>"Тестов Василь Олександрович",
          'org'=>"Міжнародна громадська організація «Українське козацтво»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Apasov.pdf"),
    array('id'=>2, 'name'=>"Тесталий Тарас Геннадійович",
          'org'=>"ВГО «Асоціація правників України»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Bezpaluy.pdf"),
    array('id'=>3, 'name'=>"Тесто Тарас Орестович",
          'org'=>"«Центр правових та політичних досліджень «СІМ»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Boyko.pdf"),
    array('id'=>4, 'name'=>"Тестін Максим Якович",
          'org'=>"«Центр правового аналізу та дослідження політичних ризиків»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Boldin.pdf"),
    array('id'=>5, 'name'=>"Тестн Євген Олександрович",
          'org'=>"«Єдиний щит»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Gilin.pdf"),
    array('id'=>6, 'name'=>"Тесторенко Юрій Сергійович",
          'org'=>"«Всеукраїнська незалежна науково-дослідна експертна спілка»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Grigorenko.pdf"),
    array('id'=>7, 'name'=>"Тестенко Олексій Анатолійович",
          'org'=>"«Всеукраїнське об'єднання «Автомайдан»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Gritsenko.pdf"),
    array('id'=>8, 'name'=>"Тестанія Леван Валер'янович",
          'org'=>"ХОГПО «Опора «Слобожанщини»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Darsaniya.pdf"),
    array('id'=>9, 'name'=>"Тестк Андрій Миколайович",
          'org'=>"«Громадське об’єднання «Здорове суспільство»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Detyuk.pdf"),
    array('id'=>10, 'name'=>"Тестнко Михайло Васильович",
          'org'=>"«Центр правового аналізу та дослідження політичних ризиків»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Dyadenko.pdf"),
    array('id'=>11, 'name'=>"Тестоцький Мар’ян Богданович",
          'org'=>"«Українське товариство економічних свобод»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Zabolotskiy.pdf"),
    array('id'=>12, 'name'=>"Тесттар Степан Андрійович",
          'org'=>"«Асоціація українських моніторів дотримання прав людини в діяльності правоохоронних органів»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Zolotar.pdf"),
    array('id'=>13, 'name'=>"Тестов Сергій Володимирович",
          'org'=>"«Громадський люстраційний комітет»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Ivanov.pdf"),
    array('id'=>14, 'name'=>"Тестнєв Михайло Володимирович",
          'org'=>"«Асоціація українських моніторів дотримання прав людини в діяльності правоохоронних органів»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Kamenev.pdf"),
    array('id'=>15, 'name'=>"Тестян Ольга Олександрівна",
          'org'=>"«Молодіжна організація «Заради майбутнього України»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Kasyan.pdf"),
    array('id'=>16, 'name'=>"Тестсников Денис Вікторович",
          'org'=>"«Громадяни Дніпропетровщини»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Kolesnikov.pdf"),
    array('id'=>17, 'name'=>"Тестнна Надія Миколаївна",
          'org'=>"«Центр правового аналізу та дослідження політичних ризиків»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Korinna.pdf"),
    array('id'=>18, 'name'=>"Тесттюк Михайло Геннадійович",
          'org'=>"«Комітет з питань захисту прав потерпілих від злочинів»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Korotuk.pdf"),
    array('id'=>19, 'name'=>"Тестивін Євген Олексійович",
          'org'=>"«Асоціація українських моніторів дотримання прав людини в діяльності правоохоронних органів»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Krapuvin.pdf"),
    array('id'=>20, 'name'=>"Тестта Катерина Юріївна",
          'org'=>"Міжнародна громадська організація «Українське козацтво»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Kuvita.pdf"),
    array('id'=>21, 'name'=>"Тестнов Олександр Валерійович",
          'org'=>"«Стейтвотч»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Lemenov.pdf"),
    array('id'=>22, 'name'=>"Тестенко Наталя Сергіївна",
          'org'=>"«Центр протидії корупції в органах влади»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Mamchenko.pdf"),
    array('id'=>23, 'name'=>"Тестинюк Юрій Анатолійович",
          'org'=>"«Народна самооборона Львівщини»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Martunyk.pdf"),
    array('id'=>24, 'name'=>"Тестук Максим Едуардович",
          'org'=>"ВГО «СГОУ «Народна Рада»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Marchuk.pdf"),
    array('id'=>25, 'name'=>"Тестнич Андрій Михайлович",
          'org'=>"ВГО «Асоціація правників України»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Melanych.pdf"),
    array('id'=>26, 'name'=>"Тестах Ігор Аркадійович",
          'org'=>"ВГО «СГОУ «Народна Рада»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Mizpah.pdf"),
    array('id'=>27, 'name'=>"Тестцький Данііл Євгенович",
          'org'=>"«Молодіжна організація «Заради майбутнього України»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Novitskiy.pdf"),
    array('id'=>28, 'name'=>"Тестнов Данило Максимович",
          'org'=>"«Ерлайт»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Nosanov.pdf"),
    array('id'=>29, 'name'=>"Тестащук Віталій Степанович",
          'org'=>"Міжнародна громадська організація «Українське козацтво»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Opanashyk.pdf"),
    array('id'=>30, 'name'=>"Тества Ксенія Юріївна",
          'org'=>"ВГО «СГОУ «Народна Рада»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Perova.pdf"),
    array('id'=>31, 'name'=>"Тестаковський Володимир Володимирович",
          'org'=>"Центр політико-правових реформ",
          'link'=>"https://dbr.gov.ua/sites/default/files/Petrakovskiy.pdf"),
    array('id'=>32, 'name'=>"Тествич Ростислав Ігорович",
          'org'=>"«Український суспільно-правовий рух: демократія через право»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Popovich.pdf"),
    array('id'=>33, 'name'=>"Тестянчук Дмитро Олександрович",
          'org'=>"«Всеукраїнське об'єднання «Автомайдан»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Replyanchuk.pdf"),
    array('id'=>34, 'name'=>"Тестць Олександр Михайлович",
          'org'=>"«Спілка юристів Одеської області»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Ryabets.pdf"),
    array('id'=>35, 'name'=>"Тестнко Євген Володимирович",
          'org'=>"«Всеукраїнська організація «Авто Евро Сила»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Savenko.pdf"),
    array('id'=>36, 'name'=>"Тестла Руслан Михайлович",
          'org'=>"«Військово-патріотичне об’єднання «ВОЛЯ»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Sekela.pdf"),
    array('id'=>37, 'name'=>"Тестицька Ольга Олександрівна",
          'org'=>"«Громадяни Дніпропетровщини»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Stavitska.pdf"),
    array('id'=>38, 'name'=>"Тестіченко Костянтин Ігорович",
          'org'=>"«Молодіжна організація «Заради майбутнього України»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Udovichenko.pdf"),
    array('id'=>39, 'name'=>"Тестонюк Ярослав Миколайович",
          'org'=>"«Стейтвотч»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Khavrohyk.pdf"),
    array('id'=>40, 'name'=>"Тестинов Сергій Володимирович",
          'org'=>"«Всеукраїнське об'єднання «Автомайдан»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Khadzhunov.pdf"),
    array('id'=>41, 'name'=>"Тестенко Павло Васильович",
          'org'=>"«Громадське об’єднання «Здорове суспільство»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Shevchenko.pdf"),
    array('id'=>42, 'name'=>"Тестстак Наталія Володимирівна",
          'org'=>"«Варта 700»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Shelestak.pdf"),
    array('id'=>43, 'name'=>"Тест Ганна Сергіївна",
          'org'=>"«Громадяни Дніпропетровщини»",
          'link'=>"https://dbr.gov.ua/sites/default/files/Shylo.pdf")
);

/**
 * candidates switch
 */
$candidates = $candidates_dbr_2019;

